### PR TITLE
Update README with GitHub steps

### PR DESCRIPTION
**Pull request by JohnCodez**
Added previously mentioned Github steps we must all follow to use it correctly.

Read over it and (In the PR) let me know what changes I can make to improve it, 
If you think it's complete, or your changes have been made, approve it and leave your thoughts in the message.

Note: You can see the styled README at https://github.com/JohnCodez/Acorn/tree/feature/update-readme

### CODE REVIEW

**Comment by jalapenojames** [comment]
Great!

**Review by jalapenojames — APPROVED** [review]
Nice

**Review by KimberlyRosaly — APPROVED** [review]
I did it?

**Comment by Jkuffler** [comment]
WHOOO

**Pull request merged**
